version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    volumes:
    - ./app:/var/www/html/public
    - ./php.ini:/usr/local/etc/php/php.ini
    - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - rinha-php-de-cria
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"
  api02:
    <<: *api
    hostname: api02
  nginx:
    hostname: nginx
    image: nginx:latest
    networks:
      - rinha-php-de-cria
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
  db:
    image: postgres:latest
    hostname: db
    command: postgres -c 'max_connections=256'
    networks:
      - rinha-php-de-cria
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "400MB"

networks:
  rinha-php-de-cria:
    driver: bridge
    name: rinha-php-de-cria